# This is a catalog-info.yaml file that is used to define the template in the Backstage catalog.
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template-generic-app
  title: Tamedia App Template
  description: Scaffold an application ready to be deployed to K8s with supports for Terraform infrastructure.
  tags:
    - app
    - terraform
    - k8s
spec:
  owner: tx-pts-dai/dai-team
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this application is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    # SelectFieldFromApi can be used to fill in the blanks for the user if DAI would be providing an API for this.
    # docs: https://roadie.io/docs/scaffolder/writing-templates/#picker-from-external-api-source

    - title: Choose a location for your new repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - DND-IT
              - tx-pts-dai
  steps:
    # TODO: Replace *all* the placeholders in the template with the values provided by the user.
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./
        copyWithoutRender:
          - catalog-info.yaml
          - README.md
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl }}
          owner: ${{ parameters.owner }}

    # action: publish:github:pull-request # https://roadie.io/docs/scaffolder/writing-templates/#publishgithubpull-request to onboard existing services

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
