name: Application

on:
  push:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  pull_request:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  # TODO: test it
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        stack: [app]
        environment: <MATRIX>
    uses: tx-pts-dai/github-workflows/.github/workflows/docker-build-push-ecr.yaml@v0.9.0
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}

  plan:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        stack: [app]
        environment: <MATRIX>
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v0.16.0
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
        
  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    strategy:
      fail-fast: false
      matrix:
        stack: [app]
        environment: [dev, int, prod]
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v0.16.0
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
