name: Application

on:
  push:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  pull_request:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  # TODO: test it
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  docker_build_artifact:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/docker-build.yaml
    with:
      image_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.sha }}
      docker_context: application
      
  docker_push_ecr:
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, production]
    uses: tx-pts-dai/github-workflows/.github/workflows/docker-push-ecr.yaml@v0.16.0
    with:
      environment: ${{ matrix.environment.environment }}
      aws_region: <AWS_REGION>
      aws_role_name: cicd-iac
      aws_account_id: ${{ matrix.environment.account_id }}
      image_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.sha }}

  plan:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, production]
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v0.16.0
    with:
      environment: ${{ matrix.environment }}
      aws_account_id: ${{ matrix.environment.account_id }}
      aws_region: <AWS_REGION>
      aws_role_name: cicd-iac
      aws_oidc_role_arn: arn:xxx
      tf_dir: deploy/application
      tf_backend_configs: bucket=tf-state-269132892972 key=XXXX
      tf_var_files: deploy/application/environments/${{ matrix.environment }}.tfvars
        
  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, production]
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v0.16.0
    with:
      environment: ${{ matrix.environment }}
      aws_account_id: ${{ matrix.environment.account_id }}
      aws_region: <AWS_REGION>
      aws_role_name: cicd-iac
      aws_oidc_role_arn: arn:xxx
      tf_dir: deploy/application
      tf_backend_configs: bucket=tf-state-269132892972 key=XXXXX
      tf_var_files: deploy/application/environments/${{ matrix.environment }}.tfvars
