name: Application

on:
  push:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  pull_request:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_push:
    strategy:
      fail-fast: true
      matrix:
        accounts:
          {% for env in matrix_envs -%}
          - environment: @{{ env.name }}
            stack: app
          {% endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/docker-build-push-ecr.yaml@v0.23.0
    with:
      environment: ${{ matrix.accounts.stack }}-${{ matrix.accounts.environment }}
      docker_context: application

  plan:
    if: github.event_name == 'pull_request'
    needs: build_push
    strategy:
      fail-fast: false
      matrix:
        accounts:
          {% for env in matrix_envs -%}
          - environment: @{{ env.name }}
            stack: app
          {% endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v0.23.0
    with:
      environment: ${{ matrix.accounts.stack }}-${{ matrix.accounts.environment }}
      tf_vars: |
        image_tag="${{ github.sha }}"
        
  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: build_push
    strategy:
      fail-fast: false
      matrix:
        accounts:
          {% for env in matrix_envs -%}
          - environment: @{{ env.name }}
            stack: app
          {% endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v0.23.0
    with:
      environment: ${{ matrix.accounts.stack }}-${{ matrix.accounts.environment }}
      tf_vars: |
        image_tag="${{ github.sha }}"
