name: Application

on:
  push:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  pull_request:
    branches: [main]
    paths:
      - "application/**"
      - "deploy/application/**"
      - ".github/workflows/application.yaml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  docker_build_push_ecr:
    strategy:
      fail-fast: true
      matrix:
        {% for env in matrix_envs -%}
        - environment: @{{ env.name }}
          stack: app
        {% endfor %}

    uses: tx-pts-dai/github-workflows/.github/workflows/docker-build-push-ecr.yaml@v0.23.0
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      docker_push: ${{ github.ref_name == github.event.repository.default_branch || github.event_name == 'pull_request' }}
      docker_context: application
      image_tag: ${{ github.sha }}

  plan:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        {% for env in matrix_envs -%}
        - environment: @{{ env.name }}
          stack: app
        {% endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@v0.23.0
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
        
  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    strategy:
      fail-fast: false
      matrix:
        {% for env in matrix_envs -%}
        - environment: @{{ env.name }}
          stack: app
        {% endfor %}
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@v0.23.0
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
      tf_vars: |
        image_tag="${{ github.sha }}"
    needs: docker_build_push_ecr
